services:
  app:
    image: your-spring-boot-app:latest
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - "8080:8080"
    networks:
      - internal
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/kissa
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - db

  db:
    image: postgres:latest
    networks:
      - internal
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: kissa
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    ports:
      - "5050:90"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    depends_on:
        - db
    networks:
        - external
        - internal
  nginx:
    build:
      context: .
      dockerfile: DockerFileProxy
    container_name: nginx
    ports:
      - "80:80" # Expose port 80 to the host
    networks:
      - internal
    depends_on:
      - app

volumes:
  postgres_data:
networks:
  internal:
  external:
