package PFA.project.config.exceptions.utils;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum ExceptionCodes {
    ERROR_BAD_REQUEST("ERROR_BAD_REQUEST","ERROR.BAD.REQUEST"),
    ERROR_MEMBER_NOT_FOUND("ERROR_MEMBER_NOT_FOUND","ERROR.MEMBER.NOT.FOUND"),
    ERROR_CLIENT_NOT_FOUND("ERROR_CLIENT_NOT_FOUND","ERROR.CLIENT.NOT.FOUND"),

    ERROR_OTP_CODE_IS_WRONG("ERROR_OTP_CODE_IS_WRONG","ERROR.OTP.CODE.IS.WRONG"),
    ERROR_MEMBER_ALREADY_VERIFIED("ERROR_MEMBER_ALREADY_VERIFIED","ERROR.MEMBER.ALREADY.VERIFIED"),
    ERROR_CLIENT_ALREADY_VERIFIED("ERROR_CLIENT_ALREADY_VERIFIED","ERROR.CLIENT.ALREADY.VERIFIED"),

    ERROR_STUDENT_ALREADY_EXIST("ERROR_STUDENT_ALREADY_EXIST","ERROR.STUDENT.ALREADY.EXIST"),
    ERROR_TEACHER_ALREADY_EXIST("ERROR_TEACHER_ALREADY_EXIST","ERROR.TEACHER.ALREADY.EXIST"),


    ERROR_PASSWORD_IS_WRONG("ERROR_PASSWORD_IS_WRONG","ERROR.PASSWORD.IS.WRONG"),
    ERROR_USER_ALREADY_EXIST("ERROR_USER_ALREADY_EXIST","ERROR.USER.ALREADY.EXIST"),
    ERROR_USER_NOT_FOUND("ERROR_USER_NOT_FOUND","ERROR.USER.NOT.FOUND"),
    ERROR_FILE_IS_EMPTY("ERROR_FILE_IS_EMPTY","ERROR.FILE.IS.EMPTY"),

    ERROR_STADIUM_NOT_FOUND("ERROR_STADIUM_NOT_FOUND","ERROR.STADIUM.NOT.FOUND");



    private final String value;
    private final String message;
}
